### ISSUE TITLE
Umstellen der Sortierung wirft Filter "Fertige verbergen" raus

### ISSUE THREAD

**Issue by jmatj** [jmatj/wed2-testat#11]
- erledigte Notes mit "Fertige verbergen" verstecken
- auf by finished date klicken
- nun sind auch die erledigten Notes wieder sichtbar

**Comment by Excape** [comment]
Das gleiche Verhalten auch bei Klick auf "switch style"
Hat wohl auch einen Zusammenhang mit #9
